version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/lwilliam/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/lwilliam/data/wordpress

networks: 
  Inception:

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file:
      - .env
    ports: 
      # - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    restart: always
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - Inception
    restart: on-failure
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - 9000:9000
    env_file:
      - .env
    networks:
      - Inception
    restart: always